1: USE SALESDB;
2: 
3: -- QUESTION 1
4: CREATE TABLE STUDENT (
5:     ID INT PRIMARY KEY,
6:     FULLNAME VARCHAR(100),
7:     AGE INT
8: );
9: 
10: -- QUESTION 2
11: INSERT INTO STUDENT (ID, FULLNAME, AGE) VALUES (1, 'ALICE JOHNSON', 18);
12: INSERT INTO STUDENT (ID, FULLNAME, AGE) VALUES (2, 'BRIAN OTIENO', 19);
13: INSERT INTO STUDENT (ID, FULLNAME, AGE) VALUES (3, 'CYNTHIA MWANGI', 21);
14: 
15: -- QUESTION 3
16: UPDATE STUDENT
17: SET AGE = 20
18: WHERE ID = 2;